import type { Locale } from './i18n';

const ADMIN_COPY = {
  en: {
    analytics: {
      customers: 'Customer analytics', totalCustomers: 'Total customers', owners: 'Restaurant owners',
      suspended: 'Suspended', totalUsers: 'Total users', restaurants: 'Restaurant analytics',
      total: 'Total', published: 'Published', pending: 'Pending', verified: 'Verified',
      orders: 'Order analytics', totalOrders: 'Total orders', today: 'Today',
      cancelled: 'Cancelled', delivered: 'Delivered',
    },
    marketing: {
      promoTitle: 'Promo codes', newCode: 'New code', code: 'Code', description: 'Description',
      type: 'Type', value: 'Value', percentage: 'Percentage (%)', fixed: 'Fixed (DZD)',
      minOrder: 'Minimum order (DZD)', maxDiscount: 'Maximum discount (DZD)', noLimit: 'No limit',
      validUntil: 'Valid until', create: 'Create', cancel: 'Cancel', noPromos: 'No promo codes yet',
      used: 'Used', status: 'Status', action: 'Action', active: 'Active', inactive: 'Inactive',
      enable: 'Enable', disable: 'Disable', promoDescription: 'Summer discount',
      campaignTitle: 'Marketing campaigns', newCampaign: 'New campaign', name: 'Name',
      push: 'Push notification', email: 'Email', inApp: 'In-app banner', loyalty: 'Loyalty bonus',
      audience: 'Audience', allUsers: 'All users', customersOnly: 'Customers only',
      ownersOnly: 'Restaurant owners', inactiveUsers: 'Inactive users', message: 'Message',
      campaignName: 'Summer campaign', campaignMessage: 'Save on your next order',
      noCampaigns: 'No campaigns yet', sent: 'Sent', start: 'Start', stop: 'Stop',
      flagsTitle: 'Feature controls', flagsHint: 'Enable platform features without deploying new code.',
      noFlags: 'No feature controls configured', feature: 'Feature', rollout: 'Rollout',
      enabled: 'Enabled', disabled: 'Disabled',
      plansTitle: 'Subscription plans', newPlan: 'New plan', planName: 'Plan name',
      planType: 'Plan type', customer: 'Customer', restaurant: 'Restaurant', driver: 'Driver',
      monthlyPrice: 'Monthly price (DZD)', features: 'Features', planPlaceholder: 'Premium',
      featuresPlaceholder: 'Free delivery, priority support', noPlans: 'No subscription plans yet',
      plan: 'Plan', priceMonth: 'Price/month',
    },
    monitoring: {
      auditLogs: 'Audit logs', viewAll: 'View all', noEntries: 'No audit entries',
    },
  },
  fr: {
    analytics: {
      customers: 'Analyse des clients', totalCustomers: 'Total clients', owners: 'Propriétaires de restaurant',
      suspended: 'Suspendus', totalUsers: 'Total utilisateurs', restaurants: 'Analyse des restaurants',
      total: 'Total', published: 'Publiés', pending: 'En attente', verified: 'Vérifiés',
      orders: 'Analyse des commandes', totalOrders: 'Total commandes', today: "Aujourd’hui",
      cancelled: 'Annulées', delivered: 'Livrées',
    },
    marketing: {
      promoTitle: 'Codes promotionnels', newCode: 'Nouveau code', code: 'Code', description: 'Description',
      type: 'Type', value: 'Valeur', percentage: 'Pourcentage (%)', fixed: 'Montant fixe (DZD)',
      minOrder: 'Commande minimale (DZD)', maxDiscount: 'Remise maximale (DZD)', noLimit: 'Sans limite',
      validUntil: 'Valable jusqu’au', create: 'Créer', cancel: 'Annuler', noPromos: 'Aucun code promotionnel',
      used: 'Utilisations', status: 'Statut', action: 'Action', active: 'Actif', inactive: 'Inactif',
      enable: 'Activer', disable: 'Désactiver', promoDescription: 'Remise estivale',
      campaignTitle: 'Campagnes marketing', newCampaign: 'Nouvelle campagne', name: 'Nom',
      push: 'Notification push', email: 'E-mail', inApp: 'Bannière intégrée', loyalty: 'Bonus fidélité',
      audience: 'Audience', allUsers: 'Tous les utilisateurs', customersOnly: 'Clients uniquement',
      ownersOnly: 'Propriétaires de restaurant', inactiveUsers: 'Utilisateurs inactifs', message: 'Message',
      campaignName: 'Campagne estivale', campaignMessage: 'Économisez sur votre prochaine commande',
      noCampaigns: 'Aucune campagne', sent: 'Envois', start: 'Démarrer', stop: 'Arrêter',
      flagsTitle: 'Contrôle des fonctionnalités', flagsHint: 'Activez les fonctions de la plateforme sans nouveau déploiement.',
      noFlags: 'Aucun contrôle configuré', feature: 'Fonctionnalité', rollout: 'Déploiement',
      enabled: 'Activée', disabled: 'Désactivée',
      plansTitle: 'Formules d’abonnement', newPlan: 'Nouvelle formule', planName: 'Nom de la formule',
      planType: 'Type de formule', customer: 'Client', restaurant: 'Restaurant', driver: 'Livreur',
      monthlyPrice: 'Prix mensuel (DZD)', features: 'Avantages', planPlaceholder: 'Premium',
      featuresPlaceholder: 'Livraison gratuite, assistance prioritaire', noPlans: 'Aucune formule d’abonnement',
      plan: 'Formule', priceMonth: 'Prix/mois',
    },
    monitoring: {
      auditLogs: 'Journal d’audit', viewAll: 'Tout afficher', noEntries: 'Aucune activité enregistrée',
    },
  },
  ar: {
    analytics: {
      customers: 'تحليلات العملاء', totalCustomers: 'إجمالي العملاء', owners: 'مالكو المطاعم',
      suspended: 'الموقوفون', totalUsers: 'إجمالي المستخدمين', restaurants: 'تحليلات المطاعم',
      total: 'الإجمالي', published: 'المنشورة', pending: 'قيد المراجعة', verified: 'الموثقة',
      orders: 'تحليلات الطلبات', totalOrders: 'إجمالي الطلبات', today: 'اليوم',
      cancelled: 'الملغاة', delivered: 'المسلّمة',
    },
    marketing: {
      promoTitle: 'الرموز الترويجية', newCode: 'رمز جديد', code: 'الرمز', description: 'الوصف',
      type: 'النوع', value: 'القيمة', percentage: 'نسبة مئوية (%)', fixed: 'مبلغ ثابت (دج)',
      minOrder: 'الحد الأدنى للطلب (دج)', maxDiscount: 'أقصى خصم (دج)', noLimit: 'دون حد',
      validUntil: 'صالح إلى', create: 'إنشاء', cancel: 'إلغاء', noPromos: 'لا توجد رموز ترويجية بعد',
      used: 'مرات الاستخدام', status: 'الحالة', action: 'الإجراء', active: 'نشط', inactive: 'غير نشط',
      enable: 'تفعيل', disable: 'تعطيل', promoDescription: 'خصم صيفي',
      campaignTitle: 'الحملات التسويقية', newCampaign: 'حملة جديدة', name: 'الاسم',
      push: 'إشعار فوري', email: 'بريد إلكتروني', inApp: 'شريط داخل التطبيق', loyalty: 'مكافأة ولاء',
      audience: 'الجمهور', allUsers: 'جميع المستخدمين', customersOnly: 'العملاء فقط',
      ownersOnly: 'مالكو المطاعم', inactiveUsers: 'المستخدمون غير النشطين', message: 'الرسالة',
      campaignName: 'حملة صيفية', campaignMessage: 'وفّر في طلبك القادم',
      noCampaigns: 'لا توجد حملات بعد', sent: 'تم الإرسال', start: 'بدء', stop: 'إيقاف',
      flagsTitle: 'التحكم في الميزات', flagsHint: 'فعّل ميزات المنصة دون نشر إصدار جديد.',
      noFlags: 'لا توجد ميزات قابلة للتحكم', feature: 'الميزة', rollout: 'نسبة الإتاحة',
      enabled: 'مفعّلة', disabled: 'معطّلة',
      plansTitle: 'خطط الاشتراك', newPlan: 'خطة جديدة', planName: 'اسم الخطة',
      planType: 'نوع الخطة', customer: 'عميل', restaurant: 'مطعم', driver: 'سائق توصيل',
      monthlyPrice: 'السعر الشهري (دج)', features: 'المزايا', planPlaceholder: 'مميّزة',
      featuresPlaceholder: 'توصيل مجاني، دعم ذو أولوية', noPlans: 'لا توجد خطط اشتراك بعد',
      plan: 'الخطة', priceMonth: 'السعر/الشهر',
    },
    monitoring: {
      auditLogs: 'سجل التدقيق', viewAll: 'عرض الكل', noEntries: 'لا توجد أنشطة مسجلة',
    },
  },
} as const;

export function adminCopy(locale: Locale) {
  return ADMIN_COPY[locale] ?? ADMIN_COPY.fr;
}
